### PR TITLE
Searingfrost

### PR DESCRIPTION
**Pull request by JamesFHeath**
Moved the logic outside of functions to main. 
Removed the for loop to check input, not needed.

### CODE REVIEW

**Comment by Harshil783** [comment]
Hey! Bro Did you run the program

**Review by Harshil783 — APPROVED** [review]

**Comment by JamesFHeath** [comment]
Yea, seems to work well! You're off to a great start with Python!

**Comment by Harshil783** [comment]
Ok so I Am gonna merge it into master branch

**Comment by Harshil783** [comment]
Thanks For The Help!

**Pull request merged**
